### ISSUE TITLE
The dataset link has expired.

### ISSUE THREAD

**Issue by vincent-tx** [ziweiWWANG/EFR#2]
As title mentioned, the link has expired. If possible, could you please give us a valid link or email us?

**Comment by ziweiWWANG** [comment]
Hi Vincent,

Thank you! The link should be working now.

Let me know if you have any other questions!

Cheers,
Ziwei
________________________________
From: vincent-tx ***@***.***>
Sent: Monday, July 17, 2023 3:00:20 PM
To: ziweiWWANG/EFR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ziweiWWANG/EFR] The dataset link has expired. (Issue #2)


As title mentioned, the link has expired. If possible, could you please give us a valid link or email us?

**Comment by vincent-tx** [comment]
Thanks for your prompt reply.
